name: MacOS 10.15
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: MacOS Build
#    runs-on: macos-latest
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v3
    - name: Setting Up the MacOS Environment
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        MAC_USER_PASSWORD: ${{ secrets.MAC_USER_PASSWORD }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
        MAC_USER_NAME: ${{ secrets.MAC_USER_NAME }}
      run: source macos.sh "$MAC_USER_NAME" "$MAC_USER_PASSWORD" "$VNC_PASSWORD" "$NGROK_AUTH_TOKEN"
    - name: Connecting MacOS with Ngrok to VNC Server
      run: source IP.sh
    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2