name: Windows Server 2019

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
    - uses: actions/checkout@v3
    - name: Connect your NGROK account.
      run: | 
        .\Windows\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel.
      run: Start-Process -FilePath ".\Windows\ngrok.exe" -ArgumentList "tcp 3389 -region ${{ secrets.NGROK_REGION }}"
    - name: Create user account.
      run: cmd /c .\Windows\user-create.bat
    - name: VM Info.
      run: cmd /c .\Windows\info.bat
    - name: Keep your VM alive.
      run: cmd /c .\Windows\loop.bat
